<?php
//start slider

if(function_exists("register_field_group"))
{
  register_field_group(array (
    'id' => 'acf_slides',
    'title' => 'Sliders',
    'fields' => array (
      array (
        'key' => 'field_73c434fe8d746',
        'label' => 'Slider',
        'name' => 'slide',
        'type' => 'repeater',
        'instructions' => 'Add new slide',
        'sub_fields' => array (
          array (
            'key' => 'field_73c437928d74b',
            'label' => 'Slide Text Color',
            'name' => 'slide_text_color',
            'type' => 'select',
            'instructions' => 'Select slide text color ( only applicable if image not selected )',
            'column_width' => '',
            'choices' => array (
              'primary-text' => 'Primary Color',
              'secondary-text' => 'Secondary Color',
              'white' => 'White',
              'black-text' => 'Black',
              'grey-text' => 'Grey',
              ),
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'allow_null' => 1,
            'layout' => 'horizontal',
            ),
          array (
            'key' => 'field_73c488928d74b',
            'label' => 'Slide Background Color',
            'name' => 'slide_background_color',
            'type' => 'select',
            'instructions' => 'Select BG color ( only applicable if image not selected )',
            'column_width' => '',
            'choices' => array (
              'primary-color-bg' => 'Primary Color',
              'secondary-color-bg' => 'Secondary Color',
              'white-bg' => 'White',
              'black-bg' => 'Black',
              'grey-bg' => 'Grey',
              ),
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'allow_null' => 1,
            'layout' => 'horizontal',
            ),
          array (
            'key' => 'field_73c438868d74c',
            'label' => 'Slider Background Image',
            'name' => 'slide_background_image',
            'type' => 'image',
            'instructions' => 'Add Image to display as slide bg',
            'column_width' => '',
            'save_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            ),
          array (
            'key' => 'field_742555ae716cc',
            'label' => 'Fixed Background Image',
            'name' => 'slide_fixed_image',
            'type' => 'checkbox',
            'column_width' => '',
            'choices' => array (
              'fixed-bg' => 'Yes',
              ),
            'default_value' => '',
            'layout' => 'horizontal',
            'allow_null' => 1,
            ),
          array (
            'key' => 'field_73c432228d74b',
            'label' => 'Slide Padding',
            'name' => 'slide_padding',
            'type' => 'select',
            'instructions' => 'select slide padding',
            'column_width' => '',
            'choices' => array (
              'pd25' => '25px',
              'pd50' => '50px',
              'pd75' => '75px',
              'pd100' => '100px',
              ),
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'allow_null' => 1,
            'layout' => 'horizontal',
            ),
          array (
            'key' => 'field_74207e5048901',
            'label' => 'Slide Builder',
            'name' => 'slide_builder',
            'type' => 'repeater',
            'column_width' => '',
            'sub_fields' => array (
              array (
                'key' => 'field_74207e5748902',
                'label' => 'Column Size',
                'name' => 'slide_column_size',
                'type' => 'select',
                'column_width' => '',
                'choices' => array (
                  'medium-3' => '1/4',
                  'medium-4' => '1/3',
                  'medium-6' => '1/2',
                  'medium-8' => '2/3',
                  'medium-9' => '3/4',
                  'medium-12' => 'Full',
                  ),
                'default_value' => '',
                'allow_null' => 1,
                'layout' => 'horizontal',
                ),
              array (
                'key' => 'field_74333180716c8',
                'label' => 'Column Alignment',
                'name' => 'slide_column_alignment',
                'type' => 'select',
                'column_width' => '',
                'choices' => array (
                  'left' => 'Left',
                  'medium-centered' => 'Center',
                  'right' => 'Right',
                  ),
                'default_value' => '',
                'layout' => 'horizontal',
                ),
              array (
                'key' => 'field_74208481716ca',
                'label' => 'Column Background',
                'name' => 'slide_column_background',
                'type' => 'select',
                'allow_null' => 1,
                'column_width' => '',
                'choices' => array (
                  'primary-color-bg' => 'Primary Color',
                  'secondary-color-bg' => 'Secondary Color',
                  'white-bg' => 'White',
                  'black-bg' => 'Black',
                  'grey-bg' => 'Grey',
                  ),
                'default_value' => '',
                'layout' => 'horizontal',
                ),
              array (
                'key' => 'field_74207f3b48904',
                'label' => 'Column Title',
                'name' => 'slide_column_title',
                'type' => 'text',
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
                ),
              array (
                'key' => 'field_74208180716c8',
                'label' => 'Title Alignment',
                'name' => 'slide_title_alignment',
                'type' => 'select',
                'column_width' => '',
                'choices' => array (
                  'text-left' => 'Left',
                  'text-center' => 'Center',
                  'text-right' => 'Right',
                  ),
                'default_value' => '',
                'layout' => 'horizontal',
                ),
              array (
                'key' => 'field_74207ee248903',
                'label' => 'Column Image',
                'name' => 'slide_column_image',
                'type' => 'image',
                'instructions' => 'add image that will display above content box',
                'column_width' => '',
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                ),
              array (
                'key' => 'field_74208212716c9',
                'label' => 'Column Content',
                'name' => 'slide_column_content',
                'type' => 'wysiwyg',
                'column_width' => '',
                'default_value' => '',
                'toolbar' => 'full',
                'media_upload' => 'yes',
                ),
              array (
                'key' => 'field_74208529716cb',
                'label' => 'Content Background',
                'name' => 'slide_content_background',
                'type' => 'select',
                'allow_null' => 1,
                'instructions' => 'add background to content inside the column',
                'column_width' => '',
                'choices' => array (
                  'primary-color-bg' => 'Primary Color',
                  'secondary-color-bg' => 'Secondary Color',
                  'white-bg' => 'White',
                  'black-bg' => 'Black',
                  'grey-bg' => 'Grey',
                  ),
                'default_value' => '',
                'layout' => 'horizontal',
                ),
              array (
                'key' => 'field_742086b2716cd',
                'label' => 'Column Link',
                'name' => 'slide_column_link',
                'type' => 'page_link',
                'column_width' => '',
                'post_type' => array (
                  0 => 'all',
                  ),
                'allow_null' => 1,
                'multiple' => 0,
                ),
              array (
                'key' => 'field_742085ae716cc',
                'label' => 'Vertically Center Content',
                'name' => 'slide_vertically_center_content',
                'type' => 'checkbox',
                'column_width' => '',
                'choices' => array (
                  'vertical_align' => 'Yes',
                  ),
                'default_value' => '',
                'layout' => 'horizontal',
                ),
              ),
'row_min' => 0,
'row_limit' => '',
'layout' => 'row',
'button_label' => 'Add Column',
),
),
'row_min' => 0,
'row_limit' => '',
'layout' => 'row',
'button_label' => 'Add Slide',
),
),
'location' => array (
  array (
    array (
      'param' => 'post_type',
      'operator' => '==',
      'value' => 'page',
      'order_no' => 0,
      'group_no' => 1,
      ),
    ),
  ),
'options' => array (
  'position' => 'normal',
  'layout' => 'no_box',
  'hide_on_screen' => array (
    ),
  ),
'menu_order' => 0,
));
}


//end slider


// Add sections

if(function_exists("register_field_group"))
{
  register_field_group(array (
    'id' => 'acf_sections',
    'title' => 'Sections',
    'fields' => array (
      array (
        'key' => 'field_53c434fe8d746',
        'label' => 'Section',
        'name' => 'section',
        'type' => 'repeater',
        'instructions' => 'Add new section',
        'sub_fields' => array (
          array (
            'key' => 'field_53c437928d74b',
            'label' => 'Section Background Color',
            'name' => 'section_background_color',
            'type' => 'select',
            'instructions' => 'Select section bg color ( only applicable if image not selected )',
            'column_width' => '',
            'choices' => array (
              'primary-color-bg' => 'Primary Color',
              'secondary-color-bg' => 'Secondary Color',
              'white-bg' => 'White',
              'black-bg' => 'Black',
              'grey-bg' => 'Grey',
              ),
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'allow_null' => 1,
            'layout' => 'horizontal',
            ),
          array (
            'key' => 'field_73c489928d74b',
            'label' => 'Section Text Color',
            'name' => 'section_text_color',
            'type' => 'select',
            'instructions' => 'Select text color',
            'column_width' => '',
            'choices' => array (
              'primary-text' => 'Primary Color',
              'secondary-text' => 'Secondary Color',
              'white' => 'White',
              'black-text' => 'Black',
              'grey-text' => 'Grey',
              ),
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'allow_null' => 1,
            'layout' => 'horizontal',
            ),
          array (
            'key' => 'field_54111e5786402',
            'label' => 'Section Title',
            'name' => 'section_title',
            'type' => 'text',
            'column_width' => '',
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'formatting' => 'html',
            'maxlength' => '',
            ),
          array (
            'key' => 'field_54111e9986402',
            'label' => 'Section Class',
            'name' => 'section_class',
            'type' => 'text',
            'column_width' => '',
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'formatting' => 'html',
            'maxlength' => '',
            ),
          array (
            'key' => 'field_73gg89928d74b',
            'label' => 'Section Title Color',
            'name' => 'section_title_color',
            'type' => 'select',
            'instructions' => 'Select text color',
            'column_width' => '',
            'choices' => array (
              'primary-text' => 'Primary Color',
              'secondary-text' => 'Secondary Color',
              'white' => 'White',
              'black-text' => 'Black',
              'grey-text' => 'Grey',
              ),
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'allow_null' => 1,
            'layout' => 'horizontal',
            ),
          array (
            'key' => 'field_53c438868d74c',
            'label' => 'Section Background Image',
            'name' => 'section_background_image',
            'type' => 'image',
            'instructions' => 'Add Image to display as section bg',
            'column_width' => '',
            'save_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            ),
          array (
            'key' => 'field_542555ae716cc',
            'label' => 'Fixed Background Image',
            'name' => 'fixed_image',
            'type' => 'checkbox',
            'column_width' => '',
            'choices' => array (
              'fixed-bg' => 'Yes',
              ),
            'default_value' => '',
            'layout' => 'horizontal',
            'allow_null' => 1,
            ),
          array (
            'key' => 'field_799555ae716cc',
            'label' => 'No Row',
            'name' => 'no_row',
            'type' => 'checkbox',
            'column_width' => '',
            'choices' => array (
              'no-row' => 'Yes',
              ),
            'default_value' => '',
            'layout' => 'horizontal',
            'allow_null' => 1,
            ),
          array (
            'key' => 'field_142000ae722cc',
            'label' => 'Equalize Columns',
            'name' => 'equalize_columns',
            'type' => 'checkbox',
            'column_width' => '',
            'choices' => array (
              'equalize-this' => 'Yes',
              ),
            'default_value' => '',
            'layout' => 'horizontal',
            ),

          array (
            'key' => 'field_53c432228d74b',
            'label' => 'Section Padding',
            'name' => 'section_padding',
            'type' => 'select',
            'instructions' => 'select section padding',
            'column_width' => '',
            'choices' => array (
              'no-padding' => 'No Padding',
              'pd25' => '25px',
              'pd50' => '50px',
              'pd75' => '75px',
              'pd100' => '100px',
              ),
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'allow_null' => 1,
            'layout' => 'horizontal',
            ),
          array (
            'key' => 'field_54207e5048901',
            'label' => 'Page Builder',
            'name' => 'page_builder',
            'type' => 'repeater',
            'column_width' => '',
            'sub_fields' => array (
              array (
                'key' => 'field_54207e5748902',
                'label' => 'Column Size',
                'name' => 'column_size',
                'type' => 'select',
                'column_width' => '',
                'choices' => array (
                  'medium-3' => '1/4',
                  'medium-4' => '1/3',
                  'medium-6' => '1/2',
                  'medium-8' => '2/3',
                  'medium-9' => '3/4',
                  'medium-12' => 'Full',
                  ),
                'default_value' => '',
                'allow_null' => 1,
                'layout' => 'horizontal',
                ),
              array (
                'key' => 'field_54111e5748902',
                'label' => 'Column Class',
                'name' => 'column_class',
                'type' => 'text',
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
                ),
              array (
                'key' => 'field_54333180716c8',
                'label' => 'Column Alignment',
                'name' => 'column_alignment',
                'type' => 'select',
                'column_width' => '',
                'choices' => array (
                  'left' => 'Left',
                  'medium-centered' => 'Center',
                  'right' => 'Right',
                  ),
                'default_value' => '',
                'layout' => 'horizontal',
                ),
              array (
                'key' => 'field_53c438333d74c',
                'label' => 'Column Background Image',
                'name' => 'column_background_image',
                'type' => 'image',
                'instructions' => 'Add Image to display as section bg',
                'column_width' => '',
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                ),
              array (
                'key' => 'field_54208481716ca',
                'label' => 'Column Background Color',
                'name' => 'column_background',
                'type' => 'select',
                'allow_null' => 1,
                'column_width' => '',
                'choices' => array (
                  'primary-color-bg' => 'Primary Color',
                  'secondary-color-bg' => 'Secondary Color',
                  'white-bg' => 'White',
                  'black-bg' => 'Black',
                  'grey-bg' => 'Grey',
                  ),
                'default_value' => '',
                'layout' => 'horizontal',
                ),
              array (
                'key' => 'field_54207f3b48904',
                'label' => 'Column Title',
                'name' => 'column_title',
                'type' => 'text',
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
                ),
              array (
                'key' => 'field_54208180716c8',
                'label' => 'Title Alignment',
                'name' => 'title_alignment',
                'type' => 'select',
                'column_width' => '',
                'choices' => array (
                  'text-left' => 'Left',
                  'text-center' => 'Center',
                  'text-right' => 'Right',
                  ),
                'default_value' => '',
                'layout' => 'horizontal',
                ),
              array (
                'key' => 'field_54207ee248903',
                'label' => 'Column Image',
                'name' => 'column_image',
                'type' => 'image',
                'instructions' => 'add image that will display above content box',
                'column_width' => '',
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                ),
              array (
                'key' => 'field_54208212716c9',
                'label' => 'Column Content',
                'name' => 'column_content',
                'type' => 'wysiwyg',
                'column_width' => '',
                'default_value' => '',
                'toolbar' => 'full',
                'media_upload' => 'yes',
                ),
              array (
                'key' => 'field_54208529716cb',
                'label' => 'Content Background',
                'name' => 'content_background',
                'type' => 'select',
                'allow_null' => 1,
                'instructions' => 'add background to content inside the column',
                'column_width' => '',
                'choices' => array (
                  'primary-color-bg' => 'Primary Color',
                  'secondary-color-bg' => 'Secondary Color',
                  'white-bg' => 'White',
                  'black-bg' => 'Black',
                  'grey-bg' => 'Grey',
                  ),
                'default_value' => '',
                'layout' => 'horizontal',
                ),
              array (
                'key' => 'field_542086b2716cd',
                'label' => 'Column Link',
                'name' => 'column_link',
                'type' => 'page_link',
                'column_width' => '',
                'post_type' => array (
                  0 => 'all',
                  ),
                'allow_null' => 1,
                'multiple' => 0,
                ),
              array (
                'key' => 'field_542085ae716cc',
                'label' => 'Vertically Center Content',
                'name' => 'vertically_center_content',
                'type' => 'checkbox',
                'column_width' => '',
                'choices' => array (
                  'vertical_align' => 'Yes',
                  ),
                'default_value' => '',
                'layout' => 'horizontal',
                ),
              ),
'row_min' => 0,
'row_limit' => '',
'layout' => 'row',
'button_label' => 'Add Column',
),
),
'row_min' => 0,
'row_limit' => '',
'layout' => 'row',
'button_label' => 'Add Section',
),
),
'location' => array (
  array (
    array (
      'param' => 'post_type',
      'operator' => '==',
      'value' => 'page',
      'order_no' => 0,
      'group_no' => 1,
      ),
    ),
  ),
'options' => array (
  'position' => 'normal',
  'layout' => 'no_box',
  'hide_on_screen' => array (
    ),
  ),
'menu_order' => 0,
));
}

//end section